name: Notebook Colab Link
on:
  pull_request:
    paths:
      - '**.ipynb'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            You can view the notebook in this PR at [Google Colab](https://colab.research.google.com/github/${{ github.repository }}/blob/${{ github.head_ref }}/${{ github.event.pull_request.changed_files[0] }})
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
